alert("Bem-vindo! A seguir pediremos que informe alguns dados!")
let nome = prompt("Informe seu nome usuario")
console.log(nome)
let idade = prompt("Qual sua idade")
console.log(idade)
let idadeConfirmated = confirm("Sua idade é" + idade + "anos")

alert("Nome: " + nome)
alert("Idade: " + idade)
alert("Idade Confirmada: " + idadeConfirmated)